version: 2.1

jobs:
    install:
      docker:
        - image: 'circleci/node:latest'
      working_directory: ~/pact-mock-feed-service
      steps:
        - checkout
        - run:
            name: Install project dependencies
            command: npm install
        - run:
            name: Run contract tests
            command: npm run test
        - run:
            name: Publish the contract to Pactflow
            command: npm run pact:publish

workflows:
    version: 2.1
    build_and_contract_test:
      jobs:
        - install
